# Generated by Django 2.2.1 on 2019-05-12 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repo',
            old_name='htm_url',
            new_name='html_url',
        ),
    ]
